name: build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3' # The Go version to download (if necessary) and use.
      - run: go build
      - uses: actions/upload-artifact@v2
        with:
          name: build-binary
          path: github_actions_test_for_golang

