name: build
on: [push]
jobs:
  build-and-push:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3' # The Go version to download (if necessary) and use.
      - name: 'build'
        run: go build -o hello_world
      - name: 'upload-artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-binary
          path: hello_world

